-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 07:20:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myarchive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myarchive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myarchive` DEFAULT CHARACTER SET utf8 ;
USE `myarchive` ;

-- -----------------------------------------------------
-- Table `myarchive`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myarchive`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myarchive`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myarchive`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myarchive`.`archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myarchive`.`archives` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `number_archive` VARCHAR(500) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `image` MEDIUMTEXT NOT NULL,
  `cat_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cat_id`),
  INDEX `fk_archives_table2_idx` (`cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_archives_table2`
    FOREIGN KEY (`cat_id`)
    REFERENCES `myarchive`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
