/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.younes;

import com.younes.connection.JavaConnected;
import com.younes.entity.User;
import com.younes.service.UserService;
import com.younes.util.TexttableCenter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BOUKHTACHE
 */
public class FUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form FHome
     */
    User user;
    Connection conn;
    PreparedStatement pst=null;
    ResultSet rst=null;
    private TexttableCenter tblcenter=new TexttableCenter();
    
    public FUser() {
        initComponents();
        conn=JavaConnected.getConnectionDB();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
               jusername.requestFocus();
            } 
        });
        showAllUsers();
    }
    public void Clear(){
        jid.setText("");
        jusername.setText("");
        jpassword.setText("");
    }
    public boolean verifyFields(){
        boolean verify=false;
        if(jusername.getText().trim().isEmpty()||jpassword.getText().trim().isEmpty()){
            return verify=true;
        }else{
            verify=false;
        }
        return verify;
    }
    //show user
    private void showAllUsers(){
        DefaultTableModel table=new DefaultTableModel();
        table.addColumn("N°");table.addColumn("User Name");table.addColumn("Password");
        
        String sql="SELECT * FROM `user` ORDER BY `username` ASC";
        try {
            pst=conn.prepareStatement(sql);
            rst=pst.executeQuery();
            while(rst.next()){
                table.addRow(new Object[]{rst.getString(1),rst.getString(2),rst.getString(3)});
            }
            jtableuser.setModel(table);
            jtableuser.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jtableuser.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            for(int i=0;i<jtableuser.getColumnCount();i++){
                 jtableuser.getColumnModel().getColumn(i).setCellRenderer(tblcenter);
             }
        } catch (Exception ex) {
           ex.printStackTrace();
        }
        
    }
    //Click Table
    
    private void showInfoUsers(){
        int row=jtableuser.getSelectedRow();
        if(row==-1){
         JOptionPane.showMessageDialog(null,"choose row...!");
        }else{
        String Table_Click=(jtableuser.getModel().getValueAt(row, 0)).toString();
        int p_id=Integer.parseInt(Table_Click);
        User user=UserService.getUser(p_id);
        jid.setText(String.valueOf(user.getId()));
        jusername.setText(user.getUsername());
        jpassword.setText(user.getPassword());
        
        }
    } 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableuser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jsave = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jdelete = new javax.swing.JButton();
        jclear = new javax.swing.JButton();
        jid = new javax.swing.JTextField();
        jusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jtableuser.setGridColor(new java.awt.Color(255, 255, 255));
        jtableuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableuserMouseClicked(evt);
            }
        });
        jtableuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtableuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtableuserKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtableuser);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 230, 290));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jsave.setText("Save");
        jsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 60, -1));

        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });
        jPanel1.add(jupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jdelete.setText("Delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        jclear.setText("Clear");
        jclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearActionPerformed(evt);
            }
        });
        jPanel1.add(jclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 70, -1));
        jPanel1.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 160, -1));
        jPanel1.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("User Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 750, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void jsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveActionPerformed
         user=new User();
         String name=jusername.getText().trim();
         String pass=jpassword.getText().trim();
         if(verifyFields()){
             JOptionPane.showMessageDialog(this,  "Opps fill fields...!","Warning !", JOptionPane.ERROR_MESSAGE);
         }else{
             user.setUsername(name);
             user.setPassword(pass);
             int status=UserService.save(user);
             if(status>0){
              JOptionPane.showMessageDialog(this,  "save success","Success", JOptionPane.INFORMATION_MESSAGE);
              showAllUsers();
              Clear();
         }else{
              JOptionPane.showMessageDialog(this,  "save failed...!","Save", JOptionPane.ERROR_MESSAGE);
         }
            
         }
    }//GEN-LAST:event_jsaveActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
         user=new User();
         String name=jusername.getText().trim();
         String pass=jpassword.getText().trim();
         Long a_id=Long.parseLong(jid.getText());
         if(verifyFields()||jid.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this,  "Opps fill fields...!","Warning !", JOptionPane.ERROR_MESSAGE);
         }else{
             user.setUsername(name);
             user.setPassword(pass);
             int status=UserService.update(user,a_id);
             if(status>0){
              JOptionPane.showMessageDialog(this,  "update success","Success", JOptionPane.INFORMATION_MESSAGE);
              showAllUsers();
              Clear();
         }else{
              JOptionPane.showMessageDialog(this,  "update failed...!","Save", JOptionPane.ERROR_MESSAGE);
         }
            
         }
    }//GEN-LAST:event_jupdateActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        String iduser=jid.getText();
       if(!iduser.trim().isEmpty()){
       int msg=JOptionPane.showConfirmDialog(null, "are you sure delete...?","Delete",JOptionPane.YES_NO_OPTION);
      if(msg==0){
        Long p_id=Long.parseLong(jid.getText());
        int status=UserService.delete(p_id);
            if(status>0){
                JOptionPane.showMessageDialog(null,"delete success..!");
                showAllUsers();
                Clear();
            }else{
               JOptionPane.showMessageDialog(null,""); 
            }
        } }else{
         JOptionPane.showMessageDialog(null,"fill field...!");   
       }
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearActionPerformed
       Clear();
    }//GEN-LAST:event_jclearActionPerformed

    private void jtableuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableuserMouseClicked
           showInfoUsers();
    }//GEN-LAST:event_jtableuserMouseClicked

    private void jtableuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtableuserKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
           showInfoUsers();
       }
    }//GEN-LAST:event_jtableuserKeyPressed

    private void jtableuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtableuserKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
           showInfoUsers();
       }
    }//GEN-LAST:event_jtableuserKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jclear;
    private javax.swing.JButton jdelete;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jpassword;
    private javax.swing.JButton jsave;
    private javax.swing.JTable jtableuser;
    private javax.swing.JButton jupdate;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
